const localProducts = [
  {
    id: 1,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Cinder",
    color: "Cinder",
    condition: "New",
    box: "Original Box",
    sizes: ["9.5"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_360_Cinder_FY2903.jpg",
    gallery: ["sneaker_images/square/Yeezys_360_Cinder_FY2903.jpg"],
    sku: "FY2903"
  },
  {
    id: 2,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Dazzling Blue",
    color: "Dazzling Blue",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2022,
    img: "sneaker_images/square/Yeezys_350_Dazzling_Blue_GY7164.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Dazzling_Blue_GY7164.jpg"],
    sku: "GY7164"
  },
  {
    id: 3,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Beluga Reflective",
    color: "Beluga Reflective",
    condition: "New",
    box: "Original Box",
    sizes: ["5.5", "6", "8"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_350_Beluga_Reflective_GW1229.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Beluga_Reflective_GW1229.jpg"],
    sku: "GW1229"
  },
  {
    id: 4,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Carbon",
    color: "Carbon",
    condition: "New",
    box: "Original Box",
    sizes: ["5.5", "7", "8", "13"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_350_Carbon_FZ5000.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Carbon_FZ5000.jpg"],
    sku: "FZ5000"
  },
  {
    id: 5,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Onyx",
    color: "Onyx",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2022,
    img: "sneaker_images/square/Yeezys_350_Onyx_HQ4540.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Onyx_HQ4540.jpg"],
    sku: "HQ4540"
  },
  {
    id: 6,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Light",
    color: "Light",
    condition: "New",
    box: "Original Box",
    sizes: ["6.5", "12.5"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_350_Light_GY3438.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Light_GY3438.jpg"],
    sku: "GY3438"
  },
  {
    id: 7,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Carbon Beluga",
    color: "Carbon Beluga",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2024,
    img: "sneaker_images/square/Yeezys_350_Carbon_Beluga_HQ7045.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Carbon_Beluga_HQ7045.jpg"],
    sku: "HQ7045"
  },
  {
    id: 8,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Natural",
    color: "Natural",
    condition: "New",
    box: "Original Box",
    sizes: ["7.5"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_350_Natural_FZ5246.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Natural_FZ5246.jpg"],
    sku: "FZ5246"
  },
  {
    id: 9,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Zyon",
    color: "Zyon",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_360_Zyon_FZ1267.jpg",
    gallery: ["sneaker_images/square/Yeezys_360_Zyon_FZ1267.jpg"],
    sku: "FZ1267"
  },
  {
    id: 10,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Black Red (Infants)",
    color: "Black Red (Infants)",
    condition: "New",
    box: "Original Box",
    sizes: ["6K"],
    year: 2017,
    img: "sneaker_images/square/Yeezys_350_Infant_Black_BB6372.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Infant_Black_BB6372.jpg"],
    sku: "BB6372"
  },
  {
    id: 11,
    brand: "adidas",
    name: "adidas Yeezy 450 Dark Slate",
    color: "Dark Slate",
    condition: "New",
    box: "Original Box",
    sizes: ["11.5"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_450_Dark_Slate_GY5368.jpg",
    gallery: ["sneaker_images/square/Yeezys_450_Dark_Slate_GY5368.jpg"],
    sku: "GY5368"
  },
  {
    id: 12,
    brand: "adidas",
    name: "Yeezy Slide Onyx",
    color: "Onyx",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2022,
    img: "sneaker_images/square/Yeezys_Slide_Onyx_HQ6448.jpg",
    gallery: ["sneaker_images/square/Yeezys_Slide_Onyx_HQ6448.jpg"],
    sku: "HQ6448"
  },
  {
    id: 13,
    brand: "adidas",
    name: "Yeezy Slide Pure",
    color: "Pure (Restock Pair)",
    condition: "New",
    box: "Original Box",
    sizes: ["12", "14"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_Slide_Pure_GW1934.jpg",
    gallery: ["sneaker_images/square/Yeezys_Slide_Pure_GW1934.jpg"],
    sku: "GW1934"
  },
  {
    id: 14,
    brand: "adidas",
    name: "Yeezy Slide Ochre",
    color: "Ochre",
    condition: "New",
    box: "Original Box",
    sizes: ["13", "14"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_Slide_Ochre_GW1931.jpg",
    gallery: ["sneaker_images/square/Yeezys_Slide_Ochre_GW1931.jpg"],
    sku: "GW1931"
  },
  {
    id: 15,
    brand: "adidas",
    name: "adidas Yeezy 700 V3 Alvah",
    color: "Alvah",
    condition: "New",
    box: "Original Box",
    sizes: ["6", "6.5"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_700_Alvah_H67799.jpg",
    gallery: ["sneaker_images/square/Yeezys_700_Alvah_H67799.jpg"],
    sku: "H67799"
  },
  {
    id: 16,
    brand: "adidas",
    name: "adidas Yeezy 700 V3 Clay Brown",
    color: "Clay Brown",
    condition: "New",
    box: "Original Box",
    sizes: ["10", "10.5"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_700_Clay_Brown_GY0189.jpg",
    gallery: ["sneaker_images/square/Yeezys_700_Clay_Brown_GY0189.jpg"],
    sku: "GY0189"
  },
  {
    id: 17,
    brand: "adidas",
    name: "adidas Yeezy Boost 700 Wave Runner",
    color: "Wave Runner",
    condition: "New",
    box: "Original Box",
    sizes: ["7", "11"],
    year: 2017,
    img: "sneaker_images/square/Yeezys_700_Wave_Runner_B75571.jpg",
    gallery: ["sneaker_images/square/Yeezys_700_Wave_Runner_B75571.jpg"],
    sku: "B75571"
  },
  {
    id: 18,
    brand: "adidas",
    name: "adidas Yeezy Boost 700 MNVN Bone",
    color: "Bone",
    condition: "New",
    box: "Original Box",
    sizes: ["7.5", "4.5"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_700_MNVN_Bone_FY3729.jpg",
    gallery: ["sneaker_images/square/Yeezys_700_MNVN_Bone_FY3729.jpg"],
    sku: "FY3729"
  },
  {
    id: 19,
    brand: "adidas",
    name: "adidas Yeezy Boost 700 V2 Tephra",
    color: "Tephra",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2019,
    img: "sneaker_images/square/Yeezys_700_Tephra_FU7914.jpg",
    gallery: ["sneaker_images/square/Yeezys_700_Tephra_FU7914.jpg"],
    sku: "FU7914"
  },
  {
    id: 20,
    brand: "adidas",
    name: "adidas Yeezy 700 V3 Dark Glow",
    color: "Dark Glow",
    condition: "New",
    box: "Original Box",
    sizes: ["11"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_700_Dark_Glow_GX6144.jpg",
    gallery: ["sneaker_images/square/Yeezys_700_Dark_Glow_GX6144.jpg"],
    sku: "GX6144"
  },
  {
    id: 21,
    brand: "adidas",
    name: "adidas Yeezy 700 V3 Arzareth",
    color: "Arzareth",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_700_Arzareth_G54850.jpg",
    gallery: ["sneaker_images/square/Yeezys_700_Arzareth_G54850.jpg"],
    sku: "G54850"
  },
  {
    id: 22,
    brand: "adidas",
    name: "Yeezy Foam MX Cinder",
    color: "MX Cinder",
    condition: "New",
    box: "Original Box",
    sizes: ["7"],
    year: 2023,
    img: "sneaker_images/square/Yeezys_Foam_MX_Cinder_ID4126.jpg",
    gallery: ["sneaker_images/square/Yeezys_Foam_MX_Cinder_ID4126.jpg"],
    sku: "ID4126"
  },
  {
    id: 23,
    brand: "adidas",
    name: "Yeezy Foam MTX Moon Grey",
    color: "MXT Moon Gray",
    condition: "New",
    box: "Original Box",
    sizes: ["5"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_Foam_MTX_Moon_Grey_GV7904.jpg",
    gallery: ["sneaker_images/square/Yeezys_Foam_MTX_Moon_Grey_GV7904.jpg"],
    sku: "GV7904"
  },
  {
    id: 24,
    brand: "adidas",
    name: "Yeezy Foam Kids MX Sand Grey",
    color: "MX Sand Grey (Kids)",
    condition: "New",
    box: "Original Box",
    sizes: ["13K"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_Foam_Kids_MX_Sand_Grey_GY3970.jpg",
    gallery: ["sneaker_images/square/Yeezys_Foam_Kids_MX_Sand_Grey_GY3970.jpg"],
    sku: "GY3970"
  },
  {
    id: 25,
    brand: "adidas",
    name: "Yeezy Foam Onyx",
    color: "Onyx",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2024,
    img: "sneaker_images/square/Yeezys_Foam_Onyx_HP8739.jpg",
    gallery: ["sneaker_images/square/Yeezys_Foam_Onyx_HP8739.jpg"],
    sku: "HP8739"
  },
  {
    id: 26,
    brand: "adidas",
    name: "Yeezy Desert Boot Taupe Blue",
    color: "Taupe Blue",
    condition: "New",
    box: "Original Box",
    sizes: ["5.5"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_Desert_Boot_Taupe_Blue_GY0374.jpg",
    gallery: ["sneaker_images/square/Yeezys_Desert_Boot_Taupe_Blue_GY0374.jpg"],
    sku: "GY0374"
  },
  {
    id: 27,
    brand: "adidas",
    name: "adidas Yeezy 500 High Slate",
    color: "Slate",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2019,
    img: "sneaker_images/square/Yeezys_500_High_Slate_FW4968.jpg",
    gallery: ["sneaker_images/square/Yeezys_500_High_Slate_FW4968.jpg"],
    sku: "FW4968"
  },
  {
    id: 28,
    brand: "adidas",
    name: "adidas Yeezy 450 Cloud White",
    color: "Cloud White",
    condition: "New",
    box: "Original Box",
    sizes: ["12"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_450_Cloud_White_H68038.jpg",
    gallery: ["sneaker_images/square/Yeezys_450_Cloud_White_H68038.jpg"],
    sku: "H68038"
  },
  {
    id: 29,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Mono Ice",
    color: "Mono Ice",
    condition: "New",
    box: "Original Box",
    sizes: ["6", "8"],
    year: 2021,
    img: "sneaker_images/square/Yeezys_350_Mono_Ice_GW2869.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Mono_Ice_GW2869.jpg"],
    sku: "GW2869"
  },
  {
    id: 30,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Israfil",
    color: "Israfil",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2020,
    img: "sneaker_images/square/Yeezys_350_Israfil_FZ5421.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Israfil_FZ5421.jpg"],
    sku: "FZ5421"
  },
  {
    id: 31,
    brand: "adidas",
    name: "adidas Yeezy Boost 350 V2 Bone",
    color: "Bone",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2022,
    img: "sneaker_images/square/Yeezys_350_Bone_HQ6316.jpg",
    gallery: ["sneaker_images/square/Yeezys_350_Bone_HQ6316.jpg"],
    sku: "HQ6316"
  },
  {
    id: 32,
    brand: "Jordan",
    name: "WMNS Air Jordan 1 Low",
    color: "Marina Blue (Women's)",
    condition: "New",
    box: "Original Box",
    sizes: ["6"],
    year: 2022,
    img: "sneaker_images/square/Sheet2_WMNS_Air_Jordan_1_Low_DC0774_114.jpg",
    gallery: ["sneaker_images/square/Sheet2_WMNS_Air_Jordan_1_Low_DC0774_114.jpg"],
    sku: "DC0774-114"
  },
  {
    id: 33,
    brand: "Jordan",
    name: "Jordan 5 RetroRaging Bull Red (2021) (GS)",
    color: "Raging Bull Red (2021) (GS)",
    condition: "New",
    box: "Original Box",
    sizes: ["3.5", "4", "4.5", "6.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_5_RetroRaging_Bull_Red_2021_GS_440888_600.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_5_RetroRaging_Bull_Red_2021_GS_440888_600.jpg"],
    sku: "440888-600"
  },
  {
    id: 34,
    brand: "Jordan",
    name: "Air Jordan 1 Retro High OG",
    color: "Dark Marina Blue",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2022,
    img: "sneaker_images/square/Sheet2_Air_Jordan_1_Retro_High_OG_555088_404.jpg",
    gallery: ["sneaker_images/square/Sheet2_Air_Jordan_1_Retro_High_OG_555088_404.jpg"],
    sku: "555088-404"
  },
  {
    id: 35,
    brand: "Jordan",
    name: "Hyper Royal/Light Smoke Grey-White",
    color: "Hyper Royal Smoke Grey (GS)",
    condition: "New",
    box: "Original Box",
    sizes: ["4.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Hyper_Royal_Light_Smoke_Grey_White_575441_402.jpg",
    gallery: ["sneaker_images/square/Sheet2_Hyper_Royal_Light_Smoke_Grey_White_575441_402.jpg"],
    sku: "575441-402"
  },
  {
    id: 36,
    brand: "Jordan",
    name: "Jordan 6 UNC University Blue White",
    color: "UNC White",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2022,
    img: "sneaker_images/square/Sheet2_Jordan_6_UNC_University_Blue_White_CT8529_410.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_6_UNC_University_Blue_White_CT8529_410.jpg"],
    sku: "CT8529-410"
  },
  {
    id: 37,
    brand: "Jordan",
    name: "Jordan 1 Lucky Green/White-Sail-Black",
    color: "Lucky Green (Women's)",
    condition: "New",
    box: "Original Box",
    sizes: ["7", "12"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Jordan_1_Lucky_Green_White_Sail_Black_DB4612_300.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_1_Lucky_Green_White_Sail_Black_DB4612_300.jpg"],
    sku: "DB4612-300"
  },
  {
    id: 38,
    brand: "Jordan",
    name: "Jordan 1 Mid Black/Medium Grey-White",
    color: "White Shadow (GS)",
    condition: "New",
    box: "Original Box",
    sizes: ["7Y"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Jordan_1_Mid_Black_Medium_Grey_White_554725_073.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_1_Mid_Black_Medium_Grey_White_554725_073.jpg"],
    sku: "554725-073"
  },
  {
    id: 39,
    brand: "Jordan",
    name: "Jordan 11 Retro Jubilee 25th Anniversary",
    color: "Jubilee 25th Anniversary",
    condition: "New",
    box: "Original Box",
    sizes: ["7.5", "8", "9", "11", "12", "13"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Jordan_11_Retro_Jubilee_25th_Anniversary_CT8012_011.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_11_Retro_Jubilee_25th_Anniversary_CT8012_011.jpg"],
    sku: "CT8012-011"
  },
  {
    id: 40,
    brand: "Nike",
    name: "Air Max 97 Undefeated Militia Green/Orange Blaze/White/Black",
    color: "Undefeated Militia Green (2020)",
    condition: "New",
    box: "Original Box",
    sizes: ["9.5"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Air_Max_97_Undefeated_Militia_Green_Orange_Blaze_White_Black_DC4830_300.jpg",
    gallery: ["sneaker_images/square/Sheet2_Air_Max_97_Undefeated_Militia_Green_Orange_Blaze_White_Black_DC4830_300.jpg"],
    sku: "DC4830-300"
  },
  {
    id: 41,
    brand: "Nike",
    name: "Air Max 97 Undefeated Black/Volt/Militia Green",
    color: "Undefeated Black Volt",
    condition: "New",
    box: "Original Box",
    sizes: ["9.5"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Air_Max_97_Undefeated_Black_Volt_Militia_Green_DC4830_001.jpg",
    gallery: ["sneaker_images/square/Sheet2_Air_Max_97_Undefeated_Black_Volt_Militia_Green_DC4830_001.jpg"],
    sku: "DC4830-001"
  },
  {
    id: 42,
    brand: "Jordan",
    name: "WMNS Jordan 1 High OG Black/Metalic",
    color: "Silver Toe (Women's)",
    condition: "New",
    box: "Original Box",
    sizes: ["5W"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_WMNS_Jordan_1_High_OG_Black_Metalic_CD0461_001.jpg",
    gallery: ["sneaker_images/square/Sheet2_WMNS_Jordan_1_High_OG_Black_Metalic_CD0461_001.jpg"],
    sku: "CD0461-001"
  },
  {
    id: 43,
    brand: "Jordan",
    name: "WMNS Jordan 3 Retro SP A Ma Maniere",
    color: "A Ma Maniére (Women's)",
    condition: "New",
    box: "Original Box",
    sizes: ["5.5W"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_WMNS_Jordan_3_Retro_SP_A_Ma_Maniere_DH3434_110.jpg",
    gallery: ["sneaker_images/square/Sheet2_WMNS_Jordan_3_Retro_SP_A_Ma_Maniere_DH3434_110.jpg"],
    sku: "DH3434-110"
  },
  {
    id: 44,
    brand: "Jordan",
    name: "Jordan 5 Retro A Ma Maniére Dusk",
    color: "A Ma Maniére Dusk",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2023,
    img: "sneaker_images/square/Sheet2_Jordan_5_Retro_A_Ma_Mani_re_Dusk_FD1330_001.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_5_Retro_A_Ma_Mani_re_Dusk_FD1330_001.jpg"],
    sku: "FD1330-001"
  },
  {
    id: 45,
    brand: "Nike",
    name: "Air Max 90 St Patrick's Day (2021)",
    color: "St Patrick's Day (2021)",
    condition: "New",
    box: "Original Box",
    sizes: ["11.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Air_Max_90_St_Patrick_s_Day_2021_DD8555_300.jpg",
    gallery: ["sneaker_images/square/Sheet2_Air_Max_90_St_Patrick_s_Day_2021_DD8555_300.jpg"],
    sku: "DD8555-300"
  },
  {
    id: 46,
    brand: "Jordan",
    name: "Jordan 5 Bel-Air White/Court Purple-Racer Pink-Ghost Green",
    color: "Alternate Bel-Air",
    condition: "New",
    box: "Original Box",
    sizes: ["7.5"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Jordan_5_Bel_Air_White_Court_Purple_Racer_Pink_Ghost_Green_DB3335_100.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_5_Bel_Air_White_Court_Purple_Racer_Pink_Ghost_Green_DB3335_100.jpg"],
    sku: "DB3335-100"
  },
  {
    id: 47,
    brand: "adidas",
    name: "Adidas Forum Buckle Low Bad Bunny Last Forum",
    color: "Bad Bunny Last Forum",
    condition: "New",
    box: "Original Box",
    sizes: ["11"],
    year: 2022,
    img: "sneaker_images/square/Sheet2_Adidas_Forum_Buckle_Low_Bad_Bunny_Last_Forum_HQ2153.jpg",
    gallery: ["sneaker_images/square/Sheet2_Adidas_Forum_Buckle_Low_Bad_Bunny_Last_Forum_HQ2153.jpg"],
    sku: "HQ2153"
  },
  {
    id: 48,
    brand: "adidas",
    name: "Adidas Forum 84 Bape Low Green Camo",
    color: "Bape 30th Anniversary Green Camo",
    condition: "New",
    box: "Original Box",
    sizes: ["7"],
    year: 2023,
    img: "sneaker_images/square/Sheet2_Adidas_Forum_84_Bape_Low_Green_Camo_ID4771.jpg",
    gallery: ["sneaker_images/square/Sheet2_Adidas_Forum_84_Bape_Low_Green_Camo_ID4771.jpg"],
    sku: "ID4771"
  },
  {
    id: 49,
    brand: "Jordan",
    name: "Jordan 5 Retro (PS) Travis Scott British Khaki",
    color: "Travis Scott British Khaki (PS)",
    condition: "New",
    box: "Original Box",
    sizes: ["2.5Y"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_5_Retro_PS_Travis_Scott_British_Khaki_DH0693_200.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_5_Retro_PS_Travis_Scott_British_Khaki_DH0693_200.jpg"],
    sku: "DH0693-200"
  },
  {
    id: 50,
    brand: "Jordan",
    name: "Air Jordan 6 Retro Travis Scott British Khaki",
    color: "Travis Scott British Khaki",
    condition: "New",
    box: "Original Box",
    sizes: ["8", "13"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Air_Jordan_6_Retro_Travis_Scott_British_Khaki_DH0690_200.jpg",
    gallery: ["sneaker_images/square/Sheet2_Air_Jordan_6_Retro_Travis_Scott_British_Khaki_DH0690_200.jpg"],
    sku: "DH0690-200"
  },
  {
    id: 51,
    brand: "Jordan",
    name: "Air Jordan 1 Mid SE Red Black Toe",
    color: "Red Black Toe",
    condition: "New",
    box: "Original Box",
    sizes: ["10"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Air_Jordan_1_Mid_SE_Red_Black_Toe_852542_100.jpg",
    gallery: ["sneaker_images/square/Sheet2_Air_Jordan_1_Mid_SE_Red_Black_Toe_852542_100.jpg"],
    sku: "852542-100"
  },
  {
    id: 52,
    brand: "Jordan",
    name: "Jordan 1 Retro High OG Patent Bred",
    color: "Patent Bred",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_1_Retro_High_OG_Patent_Bred_555088_063.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_1_Retro_High_OG_Patent_Bred_555088_063.jpg"],
    sku: "555088-063"
  },
  {
    id: 53,
    brand: "Nike",
    name: "Nike Air Trainer 3 Viotech",
    color: "Viotech (2020)",
    condition: "New",
    box: "Original Box",
    sizes: ["7.5"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Nike_Air_Trainer_3_Viotech_CZ6393_500.jpg",
    gallery: ["sneaker_images/square/Sheet2_Nike_Air_Trainer_3_Viotech_CZ6393_500.jpg"],
    sku: "CZ6393-500"
  },
  {
    id: 54,
    brand: "Jordan",
    name: "Jordan 1 Retro High Light Smoke Grey",
    color: "Light Smoke Grey",
    condition: "New",
    box: "Original Box",
    sizes: ["10.5"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Jordan_1_Retro_High_Light_Smoke_Grey_555088_126.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_1_Retro_High_Light_Smoke_Grey_555088_126.jpg"],
    sku: "555088-126"
  },
  {
    id: 55,
    brand: "Jordan",
    name: "Jordan 4 Retro (GS) White Cement",
    color: "White Oreo (2021) (GS)",
    condition: "New",
    box: "Original Box",
    sizes: ["6.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_4_Retro_GS_White_Cement_DJ4699_100.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_4_Retro_GS_White_Cement_DJ4699_100.jpg"],
    sku: "DJ4699-100"
  },
  {
    id: 56,
    brand: "Jordan",
    name: "Jordan 4 White Cement",
    color: "White Oreo (2021)",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_4_White_Cement_CT8527_100.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_4_White_Cement_CT8527_100.jpg"],
    sku: "CT8527-100"
  },
  {
    id: 57,
    brand: "Jordan",
    name: "Jordan 6 Carmine",
    color: "Carmine (2021)",
    condition: "New",
    box: "Original Box",
    sizes: ["10", "10.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_6_Carmine_CT8529_106.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_6_Carmine_CT8529_106.jpg"],
    sku: "CT8529-106"
  },
  {
    id: 58,
    brand: "Nike",
    name: "Nike Dunk Low University Blue",
    color: "UNC (2021)",
    condition: "New",
    box: "Original Box",
    sizes: ["10"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Nike_Dunk_Low_University_Blue_DD1391_102.jpg",
    gallery: ["sneaker_images/square/Sheet2_Nike_Dunk_Low_University_Blue_DD1391_102.jpg"],
    sku: "DD1391-102"
  },
  {
    id: 59,
    brand: "Jordan",
    name: "Jordan 4 University Blue",
    color: "University Blue",
    condition: "New",
    box: "Original Box",
    sizes: ["8", "10.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_4_University_Blue_CT8527_400.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_4_University_Blue_CT8527_400.jpg"],
    sku: "CT8527-400"
  },
  {
    id: 60,
    brand: "Nike",
    name: "Nike Blazer Low / Sacai",
    color: "sacai Iron Grey",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Nike_Blazer_Low_Sacai_DD1877_002.jpg",
    gallery: ["sneaker_images/square/Sheet2_Nike_Blazer_Low_Sacai_DD1877_002.jpg"],
    sku: "DD1877-002"
  },
  {
    id: 61,
    brand: "Jordan",
    name: "Jordan 4 Tour Yellow",
    color: "Lightning (2021)",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_4_Tour_Yellow_CT8527_700.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_4_Tour_Yellow_CT8527_700.jpg"],
    sku: "CT8527-700"
  },
  {
    id: 62,
    brand: "Jordan",
    name: "Jordan 14 Low CLOT Terra Blush",
    color: "Low CLOT Terra Blush",
    condition: "New",
    box: "Original Box",
    sizes: ["6.5", "10.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Jordan_14_Low_CLOT_Terra_Blush_DC9857_200.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_14_Low_CLOT_Terra_Blush_DC9857_200.jpg"],
    sku: "DC9857-200"
  },
  {
    id: 63,
    brand: "Nike",
    name: "Nike Lebron VII Media Day",
    color: "Media Day",
    condition: "New",
    box: "Original Box",
    sizes: ["9"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Nike_Lebron_VII_Media_Day_CW2300_500.jpg",
    gallery: ["sneaker_images/square/Sheet2_Nike_Lebron_VII_Media_Day_CW2300_500.jpg"],
    sku: "CW2300-500"
  },
  {
    id: 64,
    brand: "Nike",
    name: "Air Max 90",
    color: "Supernova (2020)",
    condition: "New",
    box: "Original Box",
    sizes: ["11"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Air_Max_90_CW6018_001.jpg",
    gallery: ["sneaker_images/square/Sheet2_Air_Max_90_CW6018_001.jpg"],
    sku: "CW6018-001"
  },
  {
    id: 65,
    brand: "Jordan",
    name: "Jordan 1 Mid Black/Red/White",
    color: "Bred Toe",
    condition: "New",
    box: "Original Box",
    sizes: ["12"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Jordan_1_Mid_Black_Red_White_554724_066.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_1_Mid_Black_Red_White_554724_066.jpg"],
    sku: "554724-066"
  },
  {
    id: 66,
    brand: "Nike",
    name: "Nike Dunk High (PS) Black/Yellow",
    color: "Iowa (2020) (PS)",
    condition: "New",
    box: "Original Box",
    sizes: ["2Y"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Nike_Dunk_High_PS_Black_Yellow_DC9053_002.jpg",
    gallery: ["sneaker_images/square/Sheet2_Nike_Dunk_High_PS_Black_Yellow_DC9053_002.jpg"],
    sku: "DC9053-002"
  },
  {
    id: 67,
    brand: "adidas",
    name: "Adidas Forum Powerphase Bad Bunny Benito",
    color: "Bad Bunny Benito",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2022,
    img: "sneaker_images/square/Sheet2_Adidas_Forum_Powerphase_Bad_Bunny_Benito_GZ2009.jpg",
    gallery: ["sneaker_images/square/Sheet2_Adidas_Forum_Powerphase_Bad_Bunny_Benito_GZ2009.jpg"],
    sku: "GZ2009"
  },
  {
    id: 68,
    brand: "Jordan",
    name: "Jordan 5 Sail Off White",
    color: "Off-White Sail (PS)",
    condition: "New",
    box: "Original Box",
    sizes: ["2Y"],
    year: 2020,
    img: "sneaker_images/square/Sheet2_Jordan_5_Sail_Off_White_CV4827_100.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_5_Sail_Off_White_CV4827_100.jpg"],
    sku: "CV4827-100"
  },
  {
    id: 69,
    brand: "Jordan",
    name: "Jordan 4 White/Black/Grey Army",
    color: "Military Black",
    condition: "New",
    box: "Original Box",
    sizes: ["8"],
    year: 2022,
    img: "sneaker_images/square/Sheet2_Jordan_4_White_Black_Grey_Army_DH6927_111.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_4_White_Black_Grey_Army_DH6927_111.jpg"],
    sku: "DH6927-111"
  },
  {
    id: 70,
    brand: "Jordan",
    name: "Jordan 1 Spider Man",
    color: "Spider-Man Across the Spider-Verse",
    condition: "New",
    box: "Original Box",
    sizes: ["12"],
    year: 2023,
    img: "sneaker_images/square/Sheet2_Jordan_1_Spider_Man_DV1748_601.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_1_Spider_Man_DV1748_601.jpg"],
    sku: "DV1748-601"
  },
  {
    id: 71,
    brand: "Jordan",
    name: "Jordan 4 Craft Photon Dust / Patch Works",
    color: "Craft Photon Dust",
    condition: "New",
    box: "Original Box",
    sizes: ["10", "12.5"],
    year: 2023,
    img: "sneaker_images/square/Sheet2_Jordan_4_Craft_Photon_Dust_Patch_Works_DV3742_021.jpg",
    gallery: ["sneaker_images/square/Sheet2_Jordan_4_Craft_Photon_Dust_Patch_Works_DV3742_021.jpg"],
    sku: "DV3742-021"
  },
  {
    id: 72,
    brand: "Nike",
    name: "Nike Air Max 1 Clot",
    color: "CLOT Kiss of Death (2021)",
    condition: "New",
    box: "Original Box",
    sizes: ["4.5"],
    year: 2021,
    img: "sneaker_images/square/Sheet2_Nike_Air_Max_1_Clot_DD1870_100.jpg",
    gallery: ["sneaker_images/square/Sheet2_Nike_Air_Max_1_Clot_DD1870_100.jpg"],
    sku: "DD1870-100"
  }
];
