"""
swap_block.py
Replaces the local-products block in index.html with the newly generated one.
"""

import re
from pathlib import Path

HTML_FILE = Path("index.html")
NEW_BLOCK = Path("products_block.js")
BACKUP = Path("index.html.before-swap")

def main():
    html = HTML_FILE.read_text(encoding="utf-8")
    new_js = NEW_BLOCK.read_text(encoding="utf-8").strip()

    begin_marker = "/* == local-products:begin"
    end_marker = "/* == local-products:end == */"

    start_idx = html.find(begin_marker)
    end_idx = html.find(end_marker)

    if start_idx == -1 or end_idx == -1:
        print("ERROR: Could not find local-products markers in index.html")
        print("Look for these lines:")
        print("  /* == local-products:begin ... == */")
        print("  /* == local-products:end == */")
        return

    # Find the end of the end_marker line
    end_of_line = html.find("\n", end_idx)
    if end_of_line == -1:
        end_of_line = len(html)

    # Build the new block
    replacement = (
        "/* == local-products:begin (generated by generate_products.py) == */\n"
        + new_js + "\n"
        + "products.push(...localProducts);\n"
        + "/* == local-products:end == */"
    )

    # Backup original
    BACKUP.write_text(html, encoding="utf-8")

    # Replace
    new_html = html[:start_idx] + replacement + html[end_of_line:]
    HTML_FILE.write_text(new_html, encoding="utf-8")

    # Count products
    product_count = new_html.count("sku:")
    print(f"Backed up original to {BACKUP}")
    print(f"Wrote new index.html")
    print(f"Contains ~{product_count} product entries total (including originals)")

if __name__ == "__main__":
    main()